name: 'Setup fpm'
description: 'Setup the Fortran Package Manager for use in Github actions CI'
branding:
  color: purple
  icon: package
inputs:
  github-token:
    description: 'API token needed to fetch latest fpm version'
    required: false
    default: 'none'
  use-haskell:
    description: 'Whether to use the legacy Haskell implementation of fpm'
    required: false
    default: false
  fpm-version:
    description: 'The tag of an fpm release'
    required: false
    default: 'latest'
  fpm-repository:
    description: 'Github repository (url) serving fpm releases'
    required: false
    default: 'https://github.com/fortran-lang/fpm'
runs:
  using: 'node12'
  main: 'index.js'
